# Generated by Django 5.2.15 on 2026-06-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Скидка (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Промокод'),
        ),
    ]
